var arrLang = {
    "fa": {
        "DEMO": "دمو ها",
        "SHOP": "خرید",
        "ELEMENTS": "عناصر",
        "BLOG": "بلاگ",
        "PAGES": "صفحات",
        "n-b-store": "فروشگاه",
        "n-b-menu": "منو",
        "n-b-account": "اکانت",
        "cart": "چرخ",
        "SCROLL": "اسکرول نــــــرم",
        "DESIGN": "طراحی آرگونومیک",
        "BACK_FORWARD": "عقب به جلو",
        "MOUSE": "ماوس",
        "WIRELESS1": "ممبـــــــا ",
        "WIRELESS2": " بی سیم",
        "CHROMA": "ماوس کرومای کامل و راحتِ بی سیم",
        "MONEY": "69.99$ | دلار آمریکا ",
        "SHOP-BTN": "حالا خرید کن!",
        "SMART-WATCH": "ساعت هوشمند",
        "SMART-PHONE": "گوشی هوشمند",
        "GAME-CONSOLE": "کنسول بازی",
        "LAPTOP": "لپ تاپ",
        "HEADSET": "هدست",
        "ALL-IN-ONE": "کامپیوتر همه کاره",
        "W-H3": "معاملات",
        "W-H3-2": "هفتگی",
        "W-T": "الان بهترین وقت معامله است!",
        "W-T-1": "باید عجله کنی!",
        "DAYS": "517 روز",
        "NEXT": "بعدی",
        "W-R-F": "هدفون . هدست",
        "W-R-S": "اِم کی بلوتوث هدفون",
        "W-R-S-1": "هدست استریو بی سیم جبرا",
        "W-R-F-2": "کابل هندزفری . هدفون",
        "W-R-S-2": "ساعت زنگ دار دیجیتال",
        "p-i-f-p": "بازی کردن یک مهارت جدید است! ",
        "p-i-f-h2": "ایده های بازی ",
        "p-i-f-h2-1": " برای زندگی گیمر ها",
        "p-i-f-p1": " لورم ایپسوم یا طرح‌نما به متنی آزمایشی  و بی‌معنی،",
        "p-i-f-p2": "در صنعت چاپ، صفحه‌آرایی و طراحی گرافیک گفته می‌شود.",
        "B-S-H2": "پرفروش ترین",
        "G-CONSOLE": "کنسول بازی",
        "B-S-HEADSET": "هدست",
        "B-S-LAPTOP": "لپ تاپ",
        "B-S-COMPUTER": "کامپیوتر",
        "B-S-TITLE": "ساعت هوشمند اپل",
        "B-S-ALUMINUM": " ساعت آلومینیومی اپل",
        "B-S-NIKE": " ساعت نایک اپل",
        "B-S-WATCH-5": "سری 5 ساعت اپل",
        "D-G-P": "بازی کردن یک مهارت جدید است! ",
        "D-G-H2": " تجربه بازی عمیق تر ",
        "D-G-H2-1": "",
        "D-G-P1": "لورم ایپسوم یا طرح‌نما به متنی آزمایشی <br> و بی‌معنی در صنعت چاپ، صفحه‌آرایی و طراحی <br> گرافیک گفته می‌شود.",
        "n-a-h2": "محصولات جدید",
        "n-a-special": "ویژه",
        "n-a-trends": "ترند ها",
        "n-a-pop": "محبوب",
        "w-2-retina": "مک بوک پرو رتینا",
        "w-2-span": "کامپیوتر . نوت بوک",
        "w-2-surface": " سرفیس بوک مایکروسافت",
        "w-2-sur-span": "کامپیوتر . نوت بوک",
        "w-2-imac": "آی مک اپل",
        "w-2-imac-span": "کامپیوتر . دسکتاپ",
        "w-2-xbox": "کنترلر بی سیم ایکس باکس",
        "w-2-x-span": "بازی های ویدیویی",
        "p-m-h2": "عملکردِ بهتر!",
        "p-m-h2-1": "",
        "p-m-p": " لورم ایپسوم یا طرح‌نما به متنی آزمایشی و بی‌معنی در صنعت چاپ، صفحه‌آرایی و طراحی گرافیک گفته می‌شود.",
        "p-i-p1": "به دنبال چیز خاصی هستید؟",
        "p-i-h2": "جدیدترین گجت های ",
        "p-i-h2-1": "ما را کاوش کنید!",
        "p-i-p2": " لورم ایپسوم یا طرح‌نما به متنی آزمایشی <br> و بی‌معنی در صنعت چاپ، صفحه‌آرایی و طراحی <br> گرافیک گفته می‌شود.",
        "t-d-p": "محل کار",
        "t-d-h3": "!سریع باش",
        "t-d-p1": "ساعت های هوشمند",
        "t-d-h3-1": "!هوشمند باش",
        "t-d-p2": "دوربین های عکاسی",
        "t-d-h3-2": "!حرفه ای باش",
        "c-u-h3": "ارتباط با ما",
        "c-u-p1": "24.7 ساپورت",
        "address-p": "خیابان 2418 ماد، ویومینگ کامدن",
        "footer-h4": "تحویل رایگان",
        "footer-span": "برای تمام سفارشات",
        "footer-h4-1": "پرداخت امن",
        "footer-span1": "در راه پرداخت کنید",
        "footer-h4-2": "بهترین برند ها",
        "footer-span2": "بیش از 200 برند",
        "footer-h4-3": "پشتیبانی عالی",
        "footer-span3": "پشتیبانی 24/7",
        "footer-2-p": " کیت استودیو متشکل از توسعه دهندگان و طراحان جوان پرشور است که علاقه مند به ایجاد تم های هنری هستند.",
        "footer-2-p1": "جهت یابی",
        "footer-2-a1": "خانه",
        "footer-2-a2": "بلاگ",
        "footer-2-a3": "خرید",
        "footer-3-p2": "دسته بندی ها",
        "footer-3-a1": "گجت ها",
        "footer-3-a2": "کامپیوتر",
        "footer-3-a3": "تجهیزات جانبی",
        "footer-3-a4": " الکترونیک",
        "footer-4-p2": "قوانین",
        "footer-4-a1": "حریم خصوصی",
        "footer-4-a2": "شرایط و ضوابط",
        "footer-4-a3": "سیاست بازگشت",
        "footer-4-a4": "حمایت",
        "label": "ایمیل",
        "footer-btn": "اشتراک",
        "copyright": "© 2021 کیت استودیو | ساخته شده با تِتا.",

    },
    "en": {
        "DEMO": "Demos",
        "SHOP": "Shop",
        "ELEMENTS": "Elements",
        "BLOG": "Blog",
        "PAGES": "Pages",
        "pro-btn": "Buy teta. Pro",
        "n-b-store": "Shop",
        "n-b-menu": "Menu",
        "n-b-account": "Account",
        "cart": "Cart",
        "SCROLL": "Soft Scroll",
        "DESIGN": "Ergonomic Design",
        "BACK_FORWARD": "Back Forward",
        "MOUSE": "Mouse",
        "WIRELESS1": "Mamba",
        "WIRELESS2": "Wireless",
        "CHROMA": "Full Mouse Chroma and Wireless Convenience",
        "MONEY": "US $69.99",
        "SHOP-BTN": "Shop Now!",
        "NEXT": "Next >",
        "SMART-WATCH": "Smart Watch",
        "SMART-PHONE": "Smart Phone",
        "GAME-CONSOLE": "GameConsole",
        "LAPTOP": "Laptop",
        "HEADSET": "Headset",
        "ALL-IN-ONE": "All-in-one",
        "W-H3": "Weekly ",
        "W-H3-2": "Deals",
        "W-T": ".Best deals in the market",
        "W-T-1": " !You need to Hurry",
        "DAYS": "DAYS 517",
        "NEXT": "Next >",
        "W-R-F": "HEADPHONE . HEADSET",
        "W-R-S": "Mkay Bluetooth Headphones",
        "W-R-F-1": "HEADPHONE . HEADSET",
        "W-R-S-1": "Jabra Wireless Stereo Headset",
        "W-R-F-2": "HANDSFREE CABLE . HEADPHONE",
        "W-R-S-2": "Digital Alarm Clock",
        "p-i-f-p": "Playing is a new Skill",
        "p-i-f-h2": "Playing Ideals ",
        "p-i-f-h2-1": "For Gamers Life",
        "p-i-f-p1": "Lorem ipsum dolor sit amet, consectetur ",
        "p-i-f-p2": "adipiscing elit, sed do eiusmod tempor",
        "B-S-H2": "Best Selling",
        "G-CONSOLE": "Game Console",
        "B-S-HEADSET": "Headset",
        "B-S-LAPTOP": "Laptop",
        "B-S-COMPUTER": "Computer",
        "B-S-TITLE": "Apple Smart Watch",
        "B-S-ALUMINUM": "Apple Watch Aluminum",
        "B-S-NIKE": "Apple Watch Nike",
        "B-S-WATCH-5": "Apple Watch Series 5",
        "D-G-H2": "Deeper Gaming ",
        "D-G-H2-1": "Experience",
        "n-a-h2": "New Arrivals",
        "n-a-special": "Featured",
        "n-a-trends": "Trending",
        "n-a-pop": "Popular",
        "w-2-retina": "MacBook Pro Retina",
        "w-2-span": "Computer . Notebook",
        "w-2-surface": "Microsoft Surface Book",
        "w-2-imac": "Apple iMac",
        "w-2-imac-span": "Computer . Desktop",
        "w-2-xbox": "xBox Wireless Controller",
        "w-2-x-span": "Video Games",
        "p-m-h2": "Performance ",
        "p-m-h2-1": "Made Better",
        "p-i-p1": "Looking for something special?",
        "p-i-h2": "Explore Our ",
        "p-i-h2-1": "Latest Gadgets",
        "t-d-p": "Workstations",
        "t-d-h3": "Do Fast",
        "t-d-p1": "Smartwatches",
        "t-d-h3-1": "Go Smart",
        "t-d-p2": "Photo Cameras",
        "t-d-h3-2": "Be Pro",
        "c-u-h3": "Contact Us",
        "c-u-p1": "24/7 Support",
        "address-p": "2418 Maud Street, Camden Wyoming",
        "footer-h4": "Free delivery",
        "footer-span": "For all orders",
        "footer-h4-1": "Secure Payment",
        "footer-span1": "Pay as You Go",
        "footer-h4-2": "Best Brands",
        "footer-span2": "Over 200 Brands",
        "footer-h4-3": "Excellent Support",
        "footer-2-p": "Kitestedio consists of young passionate developers and designers who are interested in creating the state of art themes.",
        "footer-2-p1": "Navigation",
        "footer-2-a1": "Home",
        "footer-2-a2": "Blog",
        "footer-2-a3": "Shop",
        "footer-3-p2": "Categories",
        "footer-3-a1": "Gadgets",
        "footer-3-a2": "Computer",
        "footer-3-a3": "Accessories",
        "footer-3-a4": "Electronics",
        "footer-4-p2": "Legal",
        "footer-4-a1": "Privacy Policy",
        "footer-4-a2": "Terms and Conditions",
        "footer-4-a3": "Reurn Policy",
        "footer-4-a4": "Support",
        "label": "Eamil",
        "footer-btn": "Subscribe",
        "copyright": "©2021 KiteStudio | Made with teta."
    }
};