var arrLang = {
    "fa": {
        "DEMO": "دمو ها",
        "SHOP": "خرید",
        "ELEMENTS": "عناصر",
        "BLOG": "بلاگ",
        "PAGES": "صفحات",
        "SCROLL": "اسکرول نــــــرم",
        "DESIGN": "طراحی آرگونومیک",
        "BACK_FORWARD": "عقب به جلو",
        "MOUSE": "ماوس",
        "WIRELESS": "ممبـــــــا <br> بی سیم",
        "CHROMA": "ماوس کرومای کامل و راحتِ بی سیم",
        "MONEY": "69.99$ | دلار آمریکا ",
        "SHOP-BTN": "!حالا خرید کن",
        "SMART-WATCH": "ساعت هوشمند",
        "SMART-PHONE": "گوشی هوشمند",
        "GAME-CONSOLE": "کنسول بازی",
        "LAPTOP": "لپ تاپ",
        "HEADSET": "هدست",
        "ALL-IN-ONE": "کامپیوتر همه کاره",

    },
    "en": {
        "DEMO": "Demos",
        "SHOP": "Shop",
        "ELEMENTS": "Elements",
        "BLOG": "Blog",
        "PAGES": "Pages",
        "SCROLL": "Soft Scroll",
        "DESIGN": "Ergonomic Design",
        "BACK_FORWARD": "Back Forward",
        "MOUSE": "Mouse",
        "WIRELESS": "Mamba Wireless",
        "CHROMA": "Full Mouse Chroma<sub>TM</sub>and Wireless Convenience",
        "MONEY": "US $69.99",
        "SHOP-BTN": "Shop Now!",
        "SMART-WATCH": "Smart Watch",
        "SMART-PHONE": "Smart Phone",
        "GAME-CONSOLE": "Game Console",
        "LAPTOP": "Laptop",
        "HEADSET": "Headset",
        "ALL-IN-ONE": "All-in-one",


    }
};